# Get Python Image
FROM public.ecr.aws/bitnami/python:latest

# Instal prerequisites
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir bandit nbconvert jupyterlab -i https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /app
VOLUME /app

CMD bash -C /utils/py-docker-execute.sh
